package Swing;

import Usuarios.Administrador;
import Usuarios.Usuario;
import bbdd.ConnectionDB;
import bbdd.ElementoDAO;
import bbdd.GestorAlmacenDAO;
import static bbdd.GestorAlmacenDAO.devolverInventarioCompleto;
import bbdd.InformeDAO;
import bbdd.UbicacionDAO;
import static bbdd.UsuariosDAO.Login;
import com.mycompany.historiashardware.Elemento;
import com.mycompany.historiashardware.Ubicacion;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM112
 */
public class Interfaz extends javax.swing.JFrame {

    private Usuario user;
    private Connection con = ConnectionDB.openConnection();

    private JPopupMenu menuEstadosInventario;
    private JPopupMenu menuLocalizacionInventario;

    private JRadioButtonMenuItem disponibleButtonPopup;
    private JRadioButtonMenuItem prestadoButtonPopUp;
    private JRadioButtonMenuItem bajaButtonPopup;
    private JRadioButtonMenuItem enReparacionButtonPopup;

    /**
     * Creates new form Swing
     */
    public Interfaz() {

        initComponents();

        //crear el popup menu de los estados para la combobox del inventario
        configurarPopupMenuEstados();

        //titulo, posicion y esas cosas
        this.setTitle("HISTORIAS DEL HARDWARE");

        setLocationRelativeTo(null);

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        panelVentanas.removeAll();
        panelVentanas.repaint();
        panelVentanas.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informesButtonGroup = new javax.swing.ButtonGroup();
        prestamosButtonGroup = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        marco = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        inventarioButton = new javax.swing.JButton();
        prestamosButton = new javax.swing.JButton();
        InformesButton = new javax.swing.JButton();
        importarButton = new javax.swing.JButton();
        exportarButton = new javax.swing.JButton();
        panelVentanas = new javax.swing.JPanel();
        inventarioPanel = new javax.swing.JPanel();
        buscarField = new javax.swing.JTextField();
        filtroScrollPane = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        eliminarButton = new javax.swing.JButton();
        buscarBoton = new javax.swing.JButton();
        añadirButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        inventarioComboBox = new javax.swing.JComboBox<>();
        informesPanel = new javax.swing.JPanel();
        categoriaButton = new javax.swing.JRadioButton();
        estadoButton = new javax.swing.JRadioButton();
        localizacionButton = new javax.swing.JRadioButton();
        completoButton = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInformes = new javax.swing.JTable();
        prestamoPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPrestamo = new javax.swing.JTable();
        confirmarButtonPrestamos = new javax.swing.JButton();
        borrarButtonPrestamos = new javax.swing.JButton();
        prestamosTextField = new javax.swing.JTextField();
        prestamoButton = new javax.swing.JRadioButton();
        devolverButton = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        marco.setLayout(new java.awt.BorderLayout());

        panelBotones.setBackground(new java.awt.Color(242, 243, 217));
        panelBotones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inventarioButton.setText("INVENTARIO");
        inventarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioButtonActionPerformed(evt);
            }
        });

        prestamosButton.setText("PRÉSTAMO");
        prestamosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamosButtonActionPerformed(evt);
            }
        });

        InformesButton.setText("INFORMES");
        InformesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformesButtonActionPerformed(evt);
            }
        });

        importarButton.setText("IMPORTAR");
        importarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarButtonActionPerformed(evt);
            }
        });

        exportarButton.setText("EXPORTAR");
        exportarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(inventarioButton)
                .addGap(51, 51, 51)
                .addComponent(prestamosButton)
                .addGap(41, 41, 41)
                .addComponent(InformesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(importarButton)
                .addGap(58, 58, 58)
                .addComponent(exportarButton)
                .addGap(19, 19, 19))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventarioButton)
                    .addComponent(prestamosButton)
                    .addComponent(InformesButton)
                    .addComponent(importarButton)
                    .addComponent(exportarButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        marco.add(panelBotones, java.awt.BorderLayout.PAGE_START);

        panelVentanas.setLayout(new java.awt.CardLayout());

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Categoría", "Estado", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        filtroScrollPane.setViewportView(tablaInventario);

        eliminarButton.setText("Eliminar");

        buscarBoton.setText("Buscar");
        buscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBotonActionPerformed(evt);
            }
        });

        añadirButton.setText("Añadir");

        modificarButton.setText("Modificar");

        inventarioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Completo", "Nombre", "Estado", "Localización" }));
        inventarioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventarioPanelLayout = new javax.swing.GroupLayout(inventarioPanel);
        inventarioPanel.setLayout(inventarioPanelLayout);
        inventarioPanelLayout.setHorizontalGroup(
            inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventarioPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtroScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addComponent(buscarField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventarioPanelLayout.createSequentialGroup()
                        .addComponent(buscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(añadirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modificarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(inventarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        inventarioPanelLayout.setVerticalGroup(
            inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventarioPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventarioComboBox))
                .addGap(29, 29, 29)
                .addComponent(filtroScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añadirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panelVentanas.add(inventarioPanel, "card5");

        informesButtonGroup.add(categoriaButton);
        categoriaButton.setText("Categoría");
        categoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaButtonActionPerformed(evt);
            }
        });

        informesButtonGroup.add(estadoButton);
        estadoButton.setText("Estado");
        estadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoButtonActionPerformed(evt);
            }
        });

        informesButtonGroup.add(localizacionButton);
        localizacionButton.setText("Localización");
        localizacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizacionButtonActionPerformed(evt);
            }
        });

        informesButtonGroup.add(completoButton);
        completoButton.setText("Completo");
        completoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completoButtonActionPerformed(evt);
            }
        });

        tablaInformes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Categoría", "Estado", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaInformes);

        javax.swing.GroupLayout informesPanelLayout = new javax.swing.GroupLayout(informesPanel);
        informesPanel.setLayout(informesPanelLayout);
        informesPanelLayout.setHorizontalGroup(
            informesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informesPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(completoButton)
                .addGap(87, 87, 87)
                .addComponent(categoriaButton)
                .addGap(111, 111, 111)
                .addComponent(estadoButton)
                .addGap(93, 93, 93)
                .addComponent(localizacionButton)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(informesPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        informesPanelLayout.setVerticalGroup(
            informesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informesPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(informesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaButton)
                    .addComponent(estadoButton)
                    .addComponent(localizacionButton)
                    .addComponent(completoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        panelVentanas.add(informesPanel, "card7");

        tablaPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Categoría", "Estado", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaPrestamo);

        confirmarButtonPrestamos.setText("Confirmar");
        confirmarButtonPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonPrestamosActionPerformed(evt);
            }
        });

        borrarButtonPrestamos.setText("Borrar");
        borrarButtonPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonPrestamosActionPerformed(evt);
            }
        });

        prestamosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamosTextFieldActionPerformed(evt);
            }
        });

        prestamosButtonGroup.add(prestamoButton);
        prestamoButton.setText("Préstamo");
        prestamoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamoButtonActionPerformed(evt);
            }
        });

        prestamosButtonGroup.add(devolverButton);
        devolverButton.setText("Devolución");
        devolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout prestamoPanelLayout = new javax.swing.GroupLayout(prestamoPanel);
        prestamoPanel.setLayout(prestamoPanelLayout);
        prestamoPanelLayout.setHorizontalGroup(
            prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamoPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(prestamoPanelLayout.createSequentialGroup()
                        .addComponent(confirmarButtonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(borrarButtonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(prestamosTextField))
                .addGap(32, 32, 32)
                .addGroup(prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(devolverButton)
                    .addGroup(prestamoPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(prestamoButton)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        prestamoPanelLayout.setVerticalGroup(
            prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamoPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(prestamosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(prestamoPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(prestamoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(devolverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarButtonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarButtonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVentanas.add(prestamoPanel, "card6");

        marco.add(panelVentanas, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(marco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(marco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Miguel
    private void categoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaButtonActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showInputDialog();
        List<String> listaCategoria = ElementoDAO.mostrarCategoria(con);
        Object[] opciones = listaCategoria.toArray();
        String t = JOptionPane.showInputDialog(null, "Selecciona el estado", "Estados", JOptionPane.PLAIN_MESSAGE, null, opciones, opciones[0]).toString();
        DefaultTableModel tabla = (DefaultTableModel) tablaInformes.getModel();
        List<Elemento> listaElementos = GestorAlmacenDAO.listarInventarioTipo(con, t);
        if (listaElementos.isEmpty()) {
            tabla.setRowCount(0);
            tabla.addRow(new Object[]{null, null, null, null, null});
        } else {
            cargarInventario(tablaInformes, listaElementos);
        }


    }//GEN-LAST:event_categoriaButtonActionPerformed
    //Miguel
    private void completoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completoButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabla = (DefaultTableModel) tablaInformes.getModel();
        List<Elemento> listaElementos = GestorAlmacenDAO.devolverInventarioCompleto(con);
        if (listaElementos.isEmpty()) {
            tabla.setRowCount(0);
            tabla.addRow(new Object[]{null, null, null, null, null});
        } else {

            cargarInventario(tablaInformes, listaElementos);
        }


    }//GEN-LAST:event_completoButtonActionPerformed

    private void borrarButtonPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonPrestamosActionPerformed
        // TODO add your handling code here:

        prestamosTextField.setText("");
    }//GEN-LAST:event_borrarButtonPrestamosActionPerformed

    private void prestamosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prestamosTextFieldActionPerformed

    private void prestamoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prestamoButtonActionPerformed

    private void devolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverButtonActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_devolverButtonActionPerformed

    private void inventarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioButtonActionPerformed
        // TODO add your handling code here:

        panelVentanas.removeAll();
        panelVentanas.add(inventarioPanel);
        panelVentanas.repaint();
        panelVentanas.revalidate();
    }//GEN-LAST:event_inventarioButtonActionPerformed

    private void exportarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Guardar Informe CSV");

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos CSV", "csv");
        chooser.setFileFilter(filtro);

        int seleccion = chooser.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            String ruta = chooser.getSelectedFile().getAbsolutePath();

            if (!ruta.toLowerCase().endsWith(".csv")) {
                ruta += ".csv";
            }

            try {

                if (completoButton.isSelected()) {
                    InformeDAO.exportarCSVCompleto(con, ruta);
                } else if (categoriaButton.isSelected()) {
                    String cat = JOptionPane.showInputDialog(this, "Categoría:");
                    if (cat != null) {
                        // InformeDAO.exportarCSVPorCategoria(con, ruta, cat);
                    }
                } else if (estadoButton.isSelected()) {
                    String est = JOptionPane.showInputDialog(this, "Estado:");
                    if (est != null) {
                        // InformeDAO.exportarCSVPorEstado(con, ruta, est);
                    }
                } else if (localizacionButton.isSelected()) {
                    // InformeDAO.exportarCSVPorLocalizacion(con, ruta);
                }

                JOptionPane.showMessageDialog(this, "Exportación finalizada.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_exportarButtonActionPerformed

    private void prestamosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamosButtonActionPerformed
        // TODO add your handling code here:
        panelVentanas.removeAll();
        panelVentanas.add(prestamoPanel);
        panelVentanas.repaint();
        panelVentanas.revalidate();
    }//GEN-LAST:event_prestamosButtonActionPerformed

    private void InformesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformesButtonActionPerformed
        // TODO add your handling code here:
        panelVentanas.removeAll();
        panelVentanas.add(informesPanel);
        panelVentanas.repaint();
        panelVentanas.revalidate();
    }//GEN-LAST:event_InformesButtonActionPerformed

    private void importarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importarButtonActionPerformed

    private void inventarioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioComboBoxActionPerformed
        // TODO add your handling code here:
        String texto = buscarField.getText().trim();
        int ubi_id = 0;//utilizar para filtrar por ubicacion
        int index = inventarioComboBox.getSelectedIndex();//guardar opcion selecionada del desplegable
        List<Elemento> inventario = null;

        //llenar la coleccion segun la opcion selecionada en el combobox (sin terminar)
        switch (index) {

            case 0 -> {//inventario completo

                //llamar a listar inventario completo
                inventario = devolverInventarioCompleto(con);

                cargarInventario(tablaInventario, inventario);

            }
            case 1 -> {//inventario por nombre

                //llamar a listar inventario por nombre
                inventario = GestorAlmacenDAO.listarInventarioNombre(con, texto);

                cargarInventario(tablaInventario, inventario);

            }
            case 2 -> {//inventario por estado

                menuEstadosInventario.show(inventarioComboBox, 0, inventarioComboBox.getHeight());

                cargarInventario(tablaInventario, inventario);

            }

            case 3 -> {//inventario por ubicacion

                configurarPopUpMenuLocalizacion();

                menuLocalizacionInventario.show(inventarioComboBox, 0, inventarioComboBox.getHeight());

            }
            default -> {
            }
        }

    }//GEN-LAST:event_inventarioComboBoxActionPerformed

    private void buscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBotonActionPerformed
        // TODO add your handling code here:

        try {

        } catch (Exception e) {

        }


    }//GEN-LAST:event_buscarBotonActionPerformed

    private void confirmarButtonPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonPrestamosActionPerformed
        // TODO add your handling code here:

        String texto = prestamosTextField.getText().trim();

        //buscar elemento
        //mostrar en la tabla

    }//GEN-LAST:event_confirmarButtonPrestamosActionPerformed
    //Miguel
    private void estadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoButtonActionPerformed
        // TODO add your handling code here:
        String t = JOptionPane.showInputDialog(null, "Selecciona el estado", "Estados", JOptionPane.PLAIN_MESSAGE, null, new Object[]{"disponible", "prestado", "en_reparacion", "baja"}, "").toString();
        DefaultTableModel tabla = (DefaultTableModel) tablaInformes.getModel();
        List<Elemento> listaElementos = GestorAlmacenDAO.listarInventarioEstado(con, t);
        if (listaElementos.isEmpty()) {
            tabla.setRowCount(0);
            tabla.addRow(new Object[]{null, null, null, null, null});
        } else {

            cargarInventario(tablaInformes, listaElementos);
        }

    }//GEN-LAST:event_estadoButtonActionPerformed
    //Miguel
    private void localizacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizacionButtonActionPerformed
        // TODO add your handling code here:
        List<Integer> listaId = UbicacionDAO.mostrarTodasUbicaciones(con);

        Object[] opciones = listaId.toArray();
        int t = Integer.parseInt(JOptionPane.showInputDialog(null, "Selecciona el id de la ubicacion", "ID Ubicacion", JOptionPane.PLAIN_MESSAGE, null, opciones, opciones[0]).toString());
        DefaultTableModel tabla = (DefaultTableModel) tablaInformes.getModel();
        List<Elemento> listaElementos = GestorAlmacenDAO.listarInvetarioUbicacion(con, t);
        if (listaElementos.isEmpty()) {
            tabla.setRowCount(0);
            tabla.addRow(new Object[]{null, null, null, null, null});
        } else {

            cargarInventario(tablaInformes, listaElementos);
        }

    }//GEN-LAST:event_localizacionButtonActionPerformed

    private void ConfigurarVisibilidad() {

        //ocultar botones de admin
        añadirButton.setVisible(false);
        modificarButton.setVisible(false);
        eliminarButton.setVisible(false);

        //mostrar si el usuario registrado es admin
        if (user instanceof Administrador) {
            añadirButton.setVisible(true);
            modificarButton.setVisible(true);
            eliminarButton.setVisible(true);
        }
    }

    private void configurarPopUpMenuLocalizacion() {

        if (menuLocalizacionInventario == null) {
            menuLocalizacionInventario = new JPopupMenu();
        }

        menuLocalizacionInventario.removeAll();

        //coleccionar para gestionar duplicados
        Set<String> ubisRepetidas = new HashSet<>();

        //coleccion para ids
        List<Integer> listaIdUbis = UbicacionDAO.mostrarTodasUbicaciones(con);

        for (Integer id : listaIdUbis) {

            //colección para ubicaciones completas
            List<Ubicacion> listaUbis
                    = UbicacionDAO.mostrarUbicaciones(con, id);

            if (!listaUbis.isEmpty()) {

                Ubicacion ubicacion = listaUbis.get(0);

                String textoDesplegable;

                if (ubicacion.getDonde_esta() != null) {

                    textoDesplegable = ubicacion.getTipo() + " " + ubicacion.getDonde_esta();

                } else {

                    textoDesplegable = ubicacion.getTipo();
                }

                // meter en el desplegable si no existe 
                if (!ubisRepetidas.contains(textoDesplegable)) {

                    ubisRepetidas.add(textoDesplegable);

                    JMenuItem opcionUbi
                            = new JMenuItem(textoDesplegable);

                    //buscar segun la localizacion elegida
                    opcionUbi.addActionListener(e -> {

                        List<Elemento> inventario
                                = GestorAlmacenDAO.listarInvetarioUbicacion(
                                        con,
                                        ubicacion.getId_ubicacion()
                                );

                        cargarInventario(tablaInventario, inventario);


                    });

                    menuLocalizacionInventario.add(opcionUbi);
                }
            }
        }

    }

    //crear el popup menu para filtrar por estados en el inventario
    private void configurarPopupMenuEstados() {

        //menu pop up de los estados
        menuEstadosInventario = new JPopupMenu();

        // botones del menu
        disponibleButtonPopup = new JRadioButtonMenuItem("Disponible");
        prestadoButtonPopUp = new JRadioButtonMenuItem("Prestado");
        bajaButtonPopup = new JRadioButtonMenuItem("Baja");
        enReparacionButtonPopup = new JRadioButtonMenuItem("En reparación");

        // agrupar botones
        ButtonGroup estadosButtonGroup = new ButtonGroup();

        estadosButtonGroup.add(disponibleButtonPopup);
        estadosButtonGroup.add(prestadoButtonPopUp);
        estadosButtonGroup.add(bajaButtonPopup);
        estadosButtonGroup.add(enReparacionButtonPopup);

        // meterlos en el pop up
        menuEstadosInventario.add(disponibleButtonPopup);
        menuEstadosInventario.add(prestadoButtonPopUp);
        menuEstadosInventario.add(bajaButtonPopup);
        menuEstadosInventario.add(enReparacionButtonPopup);

        //llamar al listado correspondiente segun la opcion del popup menu
        disponibleButtonPopup.addActionListener(e -> {

            List<Elemento> inventario = GestorAlmacenDAO.listarInventarioEstado(con, "Disponible");

            cargarInventario(tablaInventario, inventario);
        });

        prestadoButtonPopUp.addActionListener(e -> {

            List<Elemento> inventario = GestorAlmacenDAO.listarInventarioEstado(con, "Prestado");

            cargarInventario(tablaInventario, inventario);
        });

        bajaButtonPopup.addActionListener(e -> {

            List<Elemento> inventario = GestorAlmacenDAO.listarInventarioEstado(con, "Baja");

            cargarInventario(tablaInventario, inventario);
        });

        enReparacionButtonPopup.addActionListener(e -> {

            List<Elemento> inventario = GestorAlmacenDAO.listarInventarioEstado(con, "En_reparacion");

            cargarInventario(tablaInventario, inventario);
        });
    }

    //poner el inventario extraido y colocarlo en la tabla que corresponda
    private void cargarInventario(JTable table, List<Elemento> inventario) {

        DefaultTableModel tabla = (DefaultTableModel) table.getModel();

        //vaciar la tabla
        tabla.setRowCount(0);

        //cargar datos
        for (Elemento elemento : inventario) {

            tabla.addRow(new Object[]{
                elemento.getNombre(),
                elemento.getDescripcion(),
                elemento.getCategoria(),
                elemento.getEstado(),
                //añadir lo de cantidad
                0
            });
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InformesButton;
    private javax.swing.JButton añadirButton;
    private javax.swing.JButton borrarButtonPrestamos;
    private javax.swing.JButton buscarBoton;
    private javax.swing.JTextField buscarField;
    private javax.swing.JRadioButton categoriaButton;
    private javax.swing.JRadioButton completoButton;
    private javax.swing.JButton confirmarButtonPrestamos;
    private javax.swing.JRadioButton devolverButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JRadioButton estadoButton;
    private javax.swing.JButton exportarButton;
    private javax.swing.JScrollPane filtroScrollPane;
    private javax.swing.JButton importarButton;
    private javax.swing.ButtonGroup informesButtonGroup;
    private javax.swing.JPanel informesPanel;
    private javax.swing.JButton inventarioButton;
    private javax.swing.JComboBox<String> inventarioComboBox;
    private javax.swing.JPanel inventarioPanel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton localizacionButton;
    private javax.swing.JPanel marco;
    private javax.swing.JButton modificarButton;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelVentanas;
    private javax.swing.JRadioButton prestamoButton;
    private javax.swing.JPanel prestamoPanel;
    private javax.swing.JButton prestamosButton;
    private javax.swing.ButtonGroup prestamosButtonGroup;
    private javax.swing.JTextField prestamosTextField;
    private javax.swing.JTable tablaInformes;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTable tablaPrestamo;
    // End of variables declaration//GEN-END:variables
}
