/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing;

import Usuarios.Usuario;
import bbdd.ConnectionDB;
import static bbdd.UsuariosDAO.Login;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DAM112
 */
public class Interfaz extends javax.swing.JFrame {

    private Usuario user;
    private  Connection con = ConnectionDB.openConnection();
    /**
     * Creates new form Swing
     */
    public Interfaz() {
        initComponents();
        this.setTitle("HISTORIAS DEL HARDWARE");

        panelVentanas.removeAll();
        panelVentanas.add(loginPanel);
        panelVentanas.repaint();
        panelVentanas.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informesButtonGroup = new javax.swing.ButtonGroup();
        prestamosButtonGroup = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        loginPanel = new javax.swing.JPanel();
        borrarButtonLogin = new javax.swing.JButton();
        confirmarButtonLogin = new javax.swing.JButton();
        jTextUsuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        fotoLogin = new javax.swing.JLabel();
        marco = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        inventarioButton = new javax.swing.JButton();
        prestamosButton = new javax.swing.JButton();
        InformesButton = new javax.swing.JButton();
        importarButton = new javax.swing.JButton();
        exportarButton = new javax.swing.JButton();
        panelVentanas = new javax.swing.JPanel();
        inventarioPanel = new javax.swing.JPanel();
        buscarField = new javax.swing.JTextField();
        filtroScrollPane = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        eliminarButton = new javax.swing.JButton();
        buscarBoton = new javax.swing.JButton();
        añadirButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        inventarioComboBox = new javax.swing.JComboBox<>();
        informesPanel = new javax.swing.JPanel();
        categoriaButton = new javax.swing.JRadioButton();
        estadoButton = new javax.swing.JRadioButton();
        localizacionButton = new javax.swing.JRadioButton();
        completoButton = new javax.swing.JRadioButton();
        prestamoPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPrestamo = new javax.swing.JTable();
        confirmarButtonPrestamos = new javax.swing.JButton();
        borrarButtonPrestamos = new javax.swing.JButton();
        prestamosTextField = new javax.swing.JTextField();
        prestamoButton = new javax.swing.JRadioButton();
        devolverButton = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        borrarButtonLogin.setText("Borrar");
        borrarButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonLoginActionPerformed(evt);
            }
        });

        confirmarButtonLogin.setText("Confirmar");
        confirmarButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonLoginActionPerformed(evt);
            }
        });

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        fotoLogin.setBackground(new java.awt.Color(255, 255, 255));
        fotoLogin.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(fotoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(confirmarButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(borrarButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(fotoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        getContentPane().add(loginPanel, "card2");

        marco.setLayout(new java.awt.BorderLayout());

        panelBotones.setBackground(new java.awt.Color(242, 243, 217));
        panelBotones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inventarioButton.setText("INVENTARIO");
        inventarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioButtonActionPerformed(evt);
            }
        });

        prestamosButton.setText("PRÉSTAMO");
        prestamosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamosButtonActionPerformed(evt);
            }
        });

        InformesButton.setText("INFORMES");
        InformesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformesButtonActionPerformed(evt);
            }
        });

        importarButton.setText("IMPORTAR");
        importarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarButtonActionPerformed(evt);
            }
        });

        exportarButton.setText("EXPORTAR");
        exportarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(inventarioButton)
                .addGap(51, 51, 51)
                .addComponent(prestamosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(InformesButton)
                .addGap(57, 57, 57)
                .addComponent(importarButton)
                .addGap(58, 58, 58)
                .addComponent(exportarButton)
                .addGap(19, 19, 19))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventarioButton)
                    .addComponent(prestamosButton)
                    .addComponent(InformesButton)
                    .addComponent(importarButton)
                    .addComponent(exportarButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        marco.add(panelBotones, java.awt.BorderLayout.PAGE_START);

        panelVentanas.setLayout(new java.awt.CardLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Categoría", "Estado", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        filtroScrollPane.setViewportView(jTable2);

        eliminarButton.setText("Eliminar");

        buscarBoton.setText("Buscar");
        buscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBotonActionPerformed(evt);
            }
        });

        añadirButton.setText("Añadir");

        modificarButton.setText("Modificar");

        inventarioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Completo", "Nombre", "Estado", "Localización" }));
        inventarioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventarioPanelLayout = new javax.swing.GroupLayout(inventarioPanel);
        inventarioPanel.setLayout(inventarioPanelLayout);
        inventarioPanelLayout.setHorizontalGroup(
            inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventarioPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtroScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(buscarField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventarioPanelLayout.createSequentialGroup()
                        .addComponent(buscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(añadirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modificarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(inventarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        inventarioPanelLayout.setVerticalGroup(
            inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventarioPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventarioComboBox))
                .addGap(29, 29, 29)
                .addComponent(filtroScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añadirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panelVentanas.add(inventarioPanel, "card5");

        informesButtonGroup.add(categoriaButton);
        categoriaButton.setText("Categoría");
        categoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaButtonActionPerformed(evt);
            }
        });

        informesButtonGroup.add(estadoButton);
        estadoButton.setText("Estado");

        informesButtonGroup.add(localizacionButton);
        localizacionButton.setText("Localización");

        informesButtonGroup.add(completoButton);
        completoButton.setText("Completo");
        completoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout informesPanelLayout = new javax.swing.GroupLayout(informesPanel);
        informesPanel.setLayout(informesPanelLayout);
        informesPanelLayout.setHorizontalGroup(
            informesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informesPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(completoButton)
                .addGap(87, 87, 87)
                .addComponent(categoriaButton)
                .addGap(111, 111, 111)
                .addComponent(estadoButton)
                .addGap(93, 93, 93)
                .addComponent(localizacionButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        informesPanelLayout.setVerticalGroup(
            informesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informesPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(informesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaButton)
                    .addComponent(estadoButton)
                    .addComponent(localizacionButton)
                    .addComponent(completoButton))
                .addContainerGap(430, Short.MAX_VALUE))
        );

        panelVentanas.add(informesPanel, "card7");

        tablaPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Categoría", "Estado", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaPrestamo);

        confirmarButtonPrestamos.setText("Confirmar");
        confirmarButtonPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonPrestamosActionPerformed(evt);
            }
        });

        borrarButtonPrestamos.setText("Borrar");
        borrarButtonPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonPrestamosActionPerformed(evt);
            }
        });

        prestamosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamosTextFieldActionPerformed(evt);
            }
        });

        prestamosButtonGroup.add(prestamoButton);
        prestamoButton.setText("Préstamo");
        prestamoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamoButtonActionPerformed(evt);
            }
        });

        prestamosButtonGroup.add(devolverButton);
        devolverButton.setText("Devolución");
        devolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout prestamoPanelLayout = new javax.swing.GroupLayout(prestamoPanel);
        prestamoPanel.setLayout(prestamoPanelLayout);
        prestamoPanelLayout.setHorizontalGroup(
            prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamoPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(prestamoPanelLayout.createSequentialGroup()
                        .addComponent(confirmarButtonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(borrarButtonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(prestamosTextField))
                .addGap(32, 32, 32)
                .addGroup(prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(devolverButton)
                    .addGroup(prestamoPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(prestamoButton)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        prestamoPanelLayout.setVerticalGroup(
            prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamoPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(prestamosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(prestamoPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(prestamoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(devolverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(prestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarButtonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarButtonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVentanas.add(prestamoPanel, "card6");

        marco.add(panelVentanas, java.awt.BorderLayout.CENTER);

        getContentPane().add(marco, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonLoginActionPerformed
        // TODO add your handling code here:

        jTextUsuario.setText("");
        jPassword.setText("");

    }//GEN-LAST:event_borrarButtonLoginActionPerformed

    private void confirmarButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonLoginActionPerformed
        try {
            // TODO add your handling code here:
            
            //rcoger valores del login
            String nombre = jTextUsuario.getText().trim();
            String password = new String(jPassword.getPassword());
            
            //buscar usuario en la base de datos
            Usuario usuario = Login(nombre, password, con);
            
            if (usuario != null) {
                
                this.user = usuario;
                
                //quitar ventana de login y poner el marco con el menu
                loginPanel.setVisible(false);
                marco.setVisible(true);
                panelVentanas.revalidate();
                
            } else {//popup de error de usuario
            
                JOptionPane.showMessageDialog(null, "Error de Inicio de Sesión", "EL usuario no existe", JOptionPane.ERROR_MESSAGE);
            }
            
            
            //PROVISIONAL PARA PRUEBAS
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_confirmarButtonLoginActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void categoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaButtonActionPerformed

    private void completoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completoButtonActionPerformed

    private void borrarButtonPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonPrestamosActionPerformed
        // TODO add your handling code here:
        
        prestamosTextField.setText("");
    }//GEN-LAST:event_borrarButtonPrestamosActionPerformed

    private void prestamosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prestamosTextFieldActionPerformed

    private void prestamoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prestamoButtonActionPerformed

    private void devolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverButtonActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_devolverButtonActionPerformed

    private void inventarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioButtonActionPerformed
        // TODO add your handling code here:

        panelVentanas.removeAll();
        panelVentanas.add(inventarioPanel);
        panelVentanas.repaint();
        panelVentanas.revalidate();
    }//GEN-LAST:event_inventarioButtonActionPerformed

    private void exportarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportarButtonActionPerformed

    private void prestamosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamosButtonActionPerformed
        // TODO add your handling code here:
        panelVentanas.removeAll();
        panelVentanas.add(prestamoPanel);
        panelVentanas.repaint();
        panelVentanas.revalidate();
    }//GEN-LAST:event_prestamosButtonActionPerformed

    private void InformesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformesButtonActionPerformed
        // TODO add your handling code here:
        panelVentanas.removeAll();
        panelVentanas.add(informesPanel);
        panelVentanas.repaint();
        panelVentanas.revalidate();
    }//GEN-LAST:event_InformesButtonActionPerformed

    private void importarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importarButtonActionPerformed

    private void inventarioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioComboBoxActionPerformed
        // TODO add your handling code here:

        int index = inventarioComboBox.getSelectedIndex();//guardar opcion selecionada del desplegable
        
        switch (index) {
            case 0 -> {//inventario completo

                //llamar a listar inventario completo
                
                //mostrarlo en la tabla
            }
            case 1 -> {//inventario por nombre

                //llamar a listar inventario por nombre
                
                //mostrarlo en la tabla
            }
            case 2 -> {//inventario por estado
                
                //llamar a inventario por estado
                
                //mostrar en la tabla
                
            }
            
            case 3 -> {//inventario por ubicacion
                
                //llamar a listar inventario por ubicacion
                
                //mostrar en la tabla
            
                
            }
            default -> {
                
                
            }
        }


    }//GEN-LAST:event_inventarioComboBoxActionPerformed

    private void buscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBotonActionPerformed
        // TODO add your handling code here:
        
        String texto = buscarField.getText().trim();
        
        //?? llamar a filtrar por nombre??
    }//GEN-LAST:event_buscarBotonActionPerformed

    private void confirmarButtonPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonPrestamosActionPerformed
        // TODO add your handling code here:
        
        String texto = prestamosTextField.getText().trim();
        
        //buscar elemento
        
        //mostrar en la tabla
        
    }//GEN-LAST:event_confirmarButtonPrestamosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InformesButton;
    private javax.swing.JButton añadirButton;
    private javax.swing.JButton borrarButtonLogin;
    private javax.swing.JButton borrarButtonPrestamos;
    private javax.swing.JButton buscarBoton;
    private javax.swing.JTextField buscarField;
    private javax.swing.JRadioButton categoriaButton;
    private javax.swing.JRadioButton completoButton;
    private javax.swing.JButton confirmarButtonLogin;
    private javax.swing.JButton confirmarButtonPrestamos;
    private javax.swing.JRadioButton devolverButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JRadioButton estadoButton;
    private javax.swing.JButton exportarButton;
    private javax.swing.JScrollPane filtroScrollPane;
    private javax.swing.JLabel fotoLogin;
    private javax.swing.JButton importarButton;
    private javax.swing.ButtonGroup informesButtonGroup;
    private javax.swing.JPanel informesPanel;
    private javax.swing.JButton inventarioButton;
    private javax.swing.JComboBox<String> inventarioComboBox;
    private javax.swing.JPanel inventarioPanel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JRadioButton localizacionButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel marco;
    private javax.swing.JButton modificarButton;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelVentanas;
    private javax.swing.JRadioButton prestamoButton;
    private javax.swing.JPanel prestamoPanel;
    private javax.swing.JButton prestamosButton;
    private javax.swing.ButtonGroup prestamosButtonGroup;
    private javax.swing.JTextField prestamosTextField;
    private javax.swing.JTable tablaPrestamo;
    // End of variables declaration//GEN-END:variables
}
